FROM nginx:alpine

COPY index.html /usr/share/nginx/html/



#docker build -t random9deploy/webserver-demo:1.0 .
#docker push random9deploy/webserver-demo:1.0

#create a namespace
#deploy a single pod show demo and delete
#deploy a deployment add service and delete
